### ISSUE TITLE
Main Carousal

### ISSUE THREAD

**Issue by capsule11** [Sreejit-Sengupto/ravi-fans#3]
Having padding issues in the main carousal and the video section 
In video section the padding between the yt video frame and the words are not equal.

**Comment by Sreejit-Sengupto** [comment]
Acha

**Comment by Sreejit-Sengupto** [comment]
#4 Is PR me fixes hai is issue ke, kuch changes ho to batao aur nahi ho to is issue ko close kar dena

**Comment by atulya-srivastava** [comment]
> Having padding issues in the main carousal and the video section 
> In video section the padding between the yt video frame and the words are not equal.
> 

heavy English
